# d:\PythonProjects\DataToolbox\docker-compose.yml
version: '3.8'
services:
  webapp:
    build: .
    container_name: LMDataTools
    ports:
      - "8910:8910"
    volumes:
      - ./jobs:/app/jobs
      - ./personas.json:/app/personas.json:ro
      - ./topics.json:/app/topics.json:ro
    env_file:
      - .env
    environment:
      - TZ=America/Los_Angeles

